[project]
name = "cz-kpn"
version = "5.1.1"
description = "commitizen with kpn style"
readme = "README.md"
requires-python = ">=3.10,<4.0"
license = "MIT"
authors = [{ name = "Santiago Fraire Willemoes", email = "santiago.frairewillemoes@kpn.com" }]
keywords = [
  "autorelease",
  "commitizen",
  "release-management",
]
classifiers = [
  "Development Status :: 6 - Mature",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = ["commitizen (>=4.19.0,<5.0.0)"]

[project.urls]
repository = "https://github.com/kpn/cz-kpn"

[project.entry-points."commitizen.plugin"]
cz_kpn = "cz_kpn:KPNCz"

[dependency-groups]
dev = [
  "mypy>=2,<3",
  "pytest>=9,<10",
  "ruff>=0.16,<0.17",
  "tox>=4.31.0,<5",
  "tox-uv>=1.36.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src/cz_kpn"]

[tool.hatch.build.targets.sdist.force-include]
"CHANGELOG.md" = "CHANGELOG.md"
"docs/images/commit.gif" = "docs/images/commit.gif"
"docs/images/bump.gif" = "docs/images/bump.gif"

[tool.hatch.build.targets.wheel]
include = ["src/cz_kpn"]

[tool.hatch.build.targets.wheel.sources]
"src/cz_kpn" = "cz_kpn"

[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["cz_kpn", "tests"]

[tool.uv]
default-groups = "all"
