[tox]
envlist = py311,py312,py313,py314
isolated_build = true
runner = virtualenv-pep-723

[testenv]
allowlist_externals = uv
commands_pre =
    uv sync
commands =
    pytest {posargs}
    ruff check
    mypy src

[testenv:coverage]
commands =
    pytest --cov=cz_kpn --cov-report=html --cov-report=term-missing
