#!/bin/bash -e

export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

${PREFIX}pip install -U pip

if ! [ -x "$(command -v poetry)" ] ; then
    printf "poetry missing, installing now...\n"
    ${PREFIX}pip install -U poetry
else
    export PREFIX=""
fi

${PREFIX}poetry install
