#!/usr/bin/env bash
set -e

export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

${PREFIX}ruff check src/ tests/
${PREFIX}ruff format --check src/ tests/
${PREFIX}mypy src/ tests
