name: Release package to Pypi

on:
  push:
    tags:
      - "[0-9].[0-9]+.[0-9]+**"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to trigger"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.13"
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ inputs.version || github.ref_name }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      - name: Install Dependencies
        run: |
          ./scripts/install
      - name: Build package
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Current version
        id: getversion
        run: |
          export CURRENT_VERSION=$(uv run cz version -p)
          echo "VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT
      - name: Sleep for 30 seconds (give time to pypi to publish package)
        run: sleep 40s
        shell: bash
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        if: "${{ steps.getversion.outputs.VERSION != '' }}"
        with:
          context: .
          push: true
          tags: |
            kpnnl/cz-kpn:${{ steps.getversion.outputs.VERSION }}
