name: Test

on: [pull_request]

jobs:
  build:
    name: "🧪 | 🖥️ ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      - name: Install Dependencies
        run: |
          ./scripts/install
      - name: Test and Lint
        run: |
          ./scripts/lint
          ./scripts/test
